apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: tenant-red
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: tenant-blue
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-observer
  namespace: obs-system
